; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; PlatformIO Project Configuration File for Slave Node (ESP32-CAM AI-Thinker)

[env:esp32cam]
platform = espressif32
board = esp32cam
framework = arduino
monitor_speed = 115200

; Increase the upload speed to 921600 for faster firmware flashing
upload_speed = 921600

; Use a large partition scheme (Huge App) to prevent memory overflow when running camera-intensive applications
board_build.partitions = huge_app.csv

build_flags = 
    -D BOARD_HAS_PSRAM
    -D CORE_DEBUG_LEVEL=3

    ; Force the chip to apply the AI-Thinker-specific PSRAM buffer workaround
    -mfix-esp32-psram-cache-issue

lib_deps = 
    bblanchon/ArduinoJson@^7.0.4