[env:esp32-s3-cam-n16r8]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

; === OVERRIDE MEMORY CONFIGURATION FOR N16R8 ===
; 1. Khai báo dung lượng Flash 16MB
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv

; 2. Kích hoạt 8MB PSRAM (Chuẩn QIO_OPI của chip N16R8)
board_build.arduino.memory_type = qio_opi 

; 3. Các cờ (Flags) biên dịch
build_flags = 
    -D BOARD_HAS_PSRAM
    -D CORE_DEBUG_LEVEL=3
    
; 4. Thư viện
lib_deps = 
    bblanchon/ArduinoJson@^7.0.4